name: worker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get GitHub Action runner IP
        id: runner_ip
        run: |
          echo "runner_ip=$(curl -s http://checkip.amazonaws.com)" >> $GITHUB_ENV

      - name: Allow GitHub Actions IP in Azure NSG
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az network nsg rule create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --nsg-name ${{ secrets.AZURE_NSG_NAME }} \
            --name AllowGitHubActions \
            --priority 100 \
            --source-address-prefixes ${{ env.runner_ip }} \
            --destination-port-ranges 22 \
            --access Allow \
            --protocol Tcp \
            --direction Inbound

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /app
            git pull origin main
            pkill -f './main' || true
            ./deploy_script.sh
          EOF

      - name: Remove GitHub Actions IP from Azure NSG
        if: always()
        run: |
          az network nsg rule delete \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --nsg-name ${{ secrets.AZURE_NSG_NAME }} \
            --name AllowGitHubActions
